global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - /etc/prometheus/rules.yml

scrape_configs:
  - job_name: "operator-slo-lab-controller"
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:8080"]
